(() => {
  const entries = [
    {
      version: "2026.08.28",
      build: "2026-08-28-task17-finance-web",
      date: "2026-08-28",
      title: "财务账本正式接入网站",
      features: ["新增财务一级入口，支持收入、支出、退款、分类、预算、搜索筛选和撤销删除。"],
      improvements: ["Web 与 Android 共用 Task 16 canonical ledger；离线修改先保存在本机，恢复联网后自动增量同步。"],
      fixes: ["修复财务权益到期后界面仍可编辑、重复预算和跨月预算统计边界等状态问题。"],
      security: ["财务 API 继续由服务端校验 finance_access 与稳定 user ID，客户端不能跨账户读取或修改账目。"],
    },
    {
      version: "2026.08.24",
      build: "2026-08-26-task15-cloud-only",
      date: "2026-08-24",
      title: "Production 完全云端化",
      features: ["语言判卷、日语读音、词汇补全和工具偏好已迁移到 Pages Functions、D1 与 Workers AI。"],
      improvements: ["错题 PDF 改为浏览器本地生成；规则、词典和缓存命中时不会调用 AI。"],
      fixes: ["只有 D1 canonical session 的稳定终态错误会清除登录；业务 401、AI、网络或依赖故障不再误踢用户。"],
      security: ["Production 已关闭本机代理、Tunnel fallback 和身份桥依赖，AI 不持久化原始答案、词表或 prompt。"],
    },
    {
      version: "2026.08.22",
      build: "2026-08-22-learning-sync-record-id",
      date: "2026-08-22",
      title: "学习数据同步兼容修复",
      features: [],
      improvements: ["旧浏览器学习记录会补全稳定 ID；单条无法识别的记录不再阻塞其余数据同步。"],
      fixes: ["修复 Task 12 切换后历史同步 tombstone 导致客户端游标无法推进的问题。"],
      security: ["继续严格校验规范 ID，仅迁移明确支持的旧格式，并按账号保持 D1 数据隔离。"],
    },
    {
      version: "2026.08.20",
      build: "2026-08-20-task11-cloud-migration",
      date: "2026-08-20",
      title: "低风险服务 Cloudflare 迁移",
      features: ["为更新日志、反馈、功能投票和学习同步增加 D1 云端实现与渐进开关。"],
      improvements: ["保留本地优先学习流程，并通过旧账户鉴权桥维持稳定用户 ID 和现有 API 契约。"],
      fixes: ["并发同步改为版本化冲突重试，避免两台设备同时写入时丢失合并结果。"],
      security: ["D1 不保存账户、密码、会话、会员、支付或原始工具内容；统计只保存聚合白名单字段。"],
    },
    {
      version: "2026.08.11.3",
      build: "2026-08-11-tool-workflows",
      date: "2026-08-11",
      title: "可配置工具工作流",
      features: ["新增本地优先的文本、CSV、图片和 ZIP 工作流，可保存、导入、导出并使用四个模板。"],
      improvements: ["批量图片逐项隔离失败，并提供步骤状态、取消运行和三种响应式布局。"],
      fixes: ["工作流配置由前后端共同执行严格版本、字段、类型和数量校验。"],
      security: ["运行、批量处理和云端配置分别复用现有会员权益，导入文件不能携带或伪造权限。"],
    },
    {
      version: "2026.08.11.2",
      build: "2026-08-11-functional-audit",
      date: "2026-08-11",
      title: "全站功能审计与工具可靠性",
      features: ["建立覆盖公开路由、用户流程、全部工具和子模式的功能审计矩阵。"],
      improvements: ["工具产物改用独立解析器验证，并补充 390px 手机端可读性检查。"],
      fixes: ["修复中文联系人二维码编码、文本分割尾部空文件和合并多余空行。"],
      security: ["持续检查敏感运行文件，并使用隔离账号、数据库和浏览器上下文执行测试。"],
    },
    {
      version: "2026.08.11.1",
      build: "2026-08-11-learning-sync",
      date: "2026-08-11",
      title: "学习数据跨设备同步",
      features: ["错题、成就、测试历史、每日目标和语言设置支持按账号增量同步。"],
      improvements: ["学习操作保持本地优先，并提供立即同步与 JSON 备份。"],
      fixes: ["删除记录通过 tombstone 防止旧设备重新恢复。"],
      security: ["同步接口按会话隔离账号，并限制记录类型、数量和大小。"],
    },
    {
      version: "2026.08.11",
      build: "2026-08-11-feedback-voting",
      date: "2026-08-11",
      title: "反馈、功能投票与支付状态一致性",
      features: ["新增登录用户反馈、管理员处理和功能建议投票。"],
      improvements: ["更新日志改为结构化数据，并在个人首页显示最新摘要。"],
      fixes: ["修复微信与支付宝订单在创建和刷新后丢失支付方式的问题。"],
      security: ["反馈接口增加字段白名单、长度限制、频率限制和隐私内容拦截。"],
    },
    {
      version: "2026.08.09",
      build: "2026-08-09-rejudge-modal",
      date: "2026-08-09",
      title: "个人首页与错题重新判定",
      features: ["登录后首页集中显示学习、会员和服务摘要。"],
      improvements: ["错题可按正式判卷规则重新作答，并在站内弹窗显示结果。"],
      fixes: ["修复答题页切换和刷新时重复推进题目的问题。"],
      security: [],
    },
    {
      version: "2026.08.02",
      build: "2026-08-02-network-resilience",
      date: "2026-08-02",
      title: "连接恢复与缓存加固",
      features: [],
      improvements: ["完善请求超时、有限重试、网络切换恢复和 Tunnel 健康判断。"],
      fixes: ["避免非关键接口失败导致整个页面无法继续使用。"],
      security: ["补充敏感运行文件检查和服务端权限回归测试。"],
    },
    {
      version: "2026.07.28",
      build: "2026-07-28-membership-tools",
      date: "2026-07-28",
      title: "会员与在线工具箱",
      features: ["提供文本、文件、图片、随机和临时工具。"],
      improvements: ["统一套餐权益展示和管理员人工充值审批。"],
      fixes: [],
      security: ["工具与临时分享接口统一执行服务端权益校验。"],
    },
  ];

  globalThis.WYJ_CHANGELOG = Object.freeze(entries.map((entry) => Object.freeze({
    ...entry,
    features: Object.freeze([...entry.features]),
    improvements: Object.freeze([...entry.improvements]),
    fixes: Object.freeze([...entry.fixes]),
    security: Object.freeze([...entry.security]),
  })));
})();
